### ISSUE TITLE
Issue with dockerfile during docker image build

### ISSUE THREAD

**Issue by Ernestas-S** [VladoPortos/create-custom-ee-for-awx#2]
Failed at this step:

 => ERROR [4/6] RUN /usr/bin/python3 -m pip install --upgrade pip          0.5s
------
 > [4/6] RUN /usr/bin/python3 -m pip install --upgrade pip:
0.468 /usr/bin/python3: No module named pip
------
Dockerfile:11
--------------------
   9 |
  10 |     # upgrade pip
  11 | >>> RUN /usr/bin/python3 -m pip install --upgrade pip
  12 |
  13 |     # install Ansible Galaxy collections

-----------------------------------------------------------------------------------------
I think dockerfile is missing something. 

Advice on the other guide, as well, please: https://devops.cisel.ch/awx-19-create-a-custom-awx-ee-docker-image

**Comment by VladoPortos** [comment]
You are right @Ernestas-S I just checked and the "latest" official execution environment does not have pip module anymore by default... whose "brilliant" idea was that I can't tell.....

I have updated the docker file to fix the issue, give it another try.

For reference I have replaced:

```
# upgrade pip
RUN /usr/bin/python3 -m pip install --upgrade pip
```

To:

```
# make sure the pip is there and upgrade it
RUN /usr/bin/python3 -m ensurepip && /usr/bin/python3 -m pip install --upgrade pip
```
