### ISSUE TITLE
Update pip install line

### ISSUE THREAD

**Issue by Ernestas-S** [VladoPortos/create-custom-ee-for-awx#3]
Consider also updating the following line:
`
RUN pip install -r /tmp/requirements.txt
`
with this:
`
RUN /usr/bin/python3 -m pip install -r /tmp/requirements.txt
`

because the default pip in the execution environment and the default Python used to run tasks can be different, and I stumbled upon error in some tasks where it said "Failed to import the required Python library <...> Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"

**Comment by VladoPortos** [comment]
Ah good catch, changed.
